{% set name = "libcpucycles" %}
{% set version = "20230115" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpucycles.cr.yp.to/libcpucycles-{{ version }}.tar.gz
  sha256: dd38c12205550216b92607f0f42727c52a0109a16af2eaa7a13835d53ebbc225

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - python
  host:
  run:

test:
  commands:
    - cpucycles-info

about:
  home: https://cpucycles.cr.yp.to/
  summary: 'libcpucycles is a public-domain microlibrary for counting CPU cycles.'
  description: |
    libcpucycles is a public-domain microlibrary for counting CPU cycles. Cycle
    counts are not as detailed as Falk diagrams but are the most precise timers
    available to typical software; they are central tools used in understanding and
    improving software performance.
  license: Public Domain
  license_file: doc/readme.md
  doc_url: https://cpucycles.cr.yp.to/api.html

extra:
  recipe-maintainers:
    - matthiasdiener
